DECLARE
  TMP_BLOB BLOB := EMPTY_BLOB();
  SRC_CHUNK RAW(12001);
BEGIN
  DBMS_LOB.CREATETEMPORARY(TMP_BLOB, TRUE);
  DBMS_LOB.OPEN(TMP_BLOB, DBMS_LOB.LOB_READWRITE);

  SRC_CHUNK := 'BBBBBBBBBBBBBBBBBBBBBBBB';

  DBMS_LOB.WRITEAPPEND(TMP_BLOB, LENGTH(SRC_CHUNK), SRC_CHUNK);
  DBMS_LOB.CLOSE(TMP_BLOB);

  --INSERT INTO TABLE_BLOB(ID, BLB) VALUES (1001, TMP_BLOB);
END;
/